---
- name: install httpd
  yum: name={{ item }} state=installed
  with_items:
    - httpd
  notify: start httpd

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ httpd_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ httpd_port }} -j ACCEPT"
  notify: restart iptables
