---
- name: install wget
  yum: name={{ item }} state=installed
  with_items:
    - wget

- name: add repository
  command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
           creates=/etc/yum.repos.d/jenkins.repo

- name: import key
  rpm_key: key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key state=present

- name: install jenkins
  yum: name={{ item }} state=installed
  with_items:
    - jenkins

- name: set JENKINS_USER to {{ JENKINS_USER }}
  lineinfile: dest=/etc/sysconfig/jenkins regexp="^JENKINS_USER" line="JENKINS_USER={{ JENKINS_USER }}"

- name: set JENKINS_PORT to {{ JENKINS_PORT }}
  lineinfile: dest=/etc/sysconfig/jenkins regexp="^JENKINS_PORT" line="JENKINS_PORT={{ JENKINS_PORT }}"
  notify: start jenkins

- name: add proxy setting to apache
  template: src=jenkins.conf.j2 dest=/etc/httpd/conf.d/jenkins.conf
            owner=apache group=apache mode=0644
  notify: restart httpd